version: 2
jobs:
  build:
    docker:
      - image: wildebeestdev/circleci-docker-image:1.3.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run: |
          SLASH=/
          NB=${CIRCLE_BRANCH//$SLASH/_}
          docker build -t wildebeestdev/face-tracking-experiment:$NB -t wildebeestdev/face-tracking-experiment:$CIRCLE_SHA1 -t wildebeestdev/face-tracking-experiment:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker push wildebeestdev/face-tracking-experiment
  deploy:
    docker:
      - image: wildebeestdev/circleci-docker-image:1.3.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /root
    steps:
      - run: |
          git clone git@github.com:wildebeestdev/k8s-config.git
          /root/k8s-config/circle-scripts/deploy.sh face-tracking-experiment $CIRCLE_SHA1 face-tracking-experiment/config face-tracking-experiment/staging/01-deployment.yaml face-tracking-experiment

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master